INSERT INTO Carrera (carrera) VALUES ("Ingeniería en Computación");
INSERT INTO Carrera (carrera) VALUES ("Arquitectura y Urbanismo");
INSERT INTO Carrera (carrera) VALUES ("Administración de Empresas");
INSERT INTO Horario(horario) VALUES ("08:00");
INSERT INTO Horario(horario) VALUES ("09:00");
INSERT INTO Horario(horario) VALUES ("10:00");
INSERT INTO Horario(horario) VALUES ("11:00");
INSERT INTO Horario(horario) VALUES ("13:00");
INSERT INTO Horario(horario) VALUES ("14:00");
INSERT INTO Horario(horario) VALUES ("15:00");
INSERT INTO Horario(horario) VALUES ("16:00");
INSERT INTO Horario(horario) VALUES ("17:00");
INSERT INTO Horario(horario) VALUES ("18:00");
INSERT INTO Horario(horario) VALUES ("19:00");
INSERT INTO Motivo (motivo) VALUES ("Académico");
INSERT INTO Motivo (motivo) VALUES ("Ajuste a la vida universitaria");
INSERT INTO Motivo (motivo) VALUES ("Proyecto de vida");
INSERT INTO Motivo (motivo) VALUES ("Pareja");
INSERT INTO Motivo (motivo) VALUES ("Sexualidad");
INSERT INTO Motivo (motivo) VALUES ("Manejo del estrés");
INSERT INTO Motivo (motivo) VALUES ("Vocacional-Profesional");
INSERT INTO Motivo (motivo) VALUES ("Autoestima");
INSERT INTO Motivo (motivo) VALUES ("Familiar");
INSERT INTO Motivo (motivo) VALUES ("Referencia");
INSERT INTO Nivel (nivel) VALUES ("Primer ingreso");
INSERT INTO Nivel (nivel) VALUES ("Segundo año");
INSERT INTO Nivel (nivel) VALUES ("Tercer año");
INSERT INTO Nivel (nivel) VALUES ("Cuarto año");
INSERT INTO Nivel (nivel) VALUES ("Quinto o más año");
INSERT INTO Referencia (referencia) VALUES ("Trabajo social");
INSERT INTO Referencia (referencia) VALUES ("Equidad de género");
INSERT INTO Referencia (referencia) VALUES ("Psicología clínica");
INSERT INTO Referencia (referencia) VALUES ("Médico");
INSERT INTO Referencia (referencia) VALUES ("Docente");
INSERT INTO Sexo (sexo) VALUES ("Hombre");
INSERT INTO Sexo (sexo) VALUES ("Mujer");
INSERT INTO Sexo (sexo) VALUES ("Otro");
INSERT INTO Urgencia (urgencia) VALUES (1);
INSERT INTO Urgencia (urgencia) VALUES (2);
INSERT INTO Urgencia (urgencia) VALUES (3);
INSERT INTO Urgencia (urgencia) VALUES (4);
INSERT INTO Urgencia (urgencia) VALUES (5);
INSERT INTO DiasSemana(diaSemana) VALUES ("Domingo");
INSERT INTO DiasSemana(diaSemana) VALUES ("Lunes");
INSERT INTO DiasSemana(diaSemana) VALUES ("Martes");
INSERT INTO DiasSemana(diaSemana) VALUES ("Miercoles");
INSERT INTO DiasSemana(diaSemana) VALUES ("Jueves");
INSERT INTO DiasSemana(diaSemana) VALUES ("Viernes");
INSERT INTO DiasSemana(diaSemana) VALUES ("Sabado");
